name: student_result_viewer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^0.1.3

  # Networking
  http: ^0.12.0+4
  dio: ^3.0.9
  data_connection_checker: ^0.3.4

  # State management
  flutter_bloc: ^3.2.0

  # Dependency Injection
  get_it: ^4.0.1
  injectable: ^0.3.0

  # Navigation
  auto_route: ^0.4.3

  # Logging
  logger: ^0.8.3

  # Data classes & json serialization
  kt_dart: ^0.7.0+1
  freezed_annotation: ^0.7.1
  json_serializable: ^3.3.0

  flushbar: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mockito: ^4.1.1

  # Generators
  build_runner: ^1.8.1
  injectable_generator: ^0.3.3
  auto_route_generator: ^0.4.3

  # Data classes
  freezed: ^0.10.4

# The following section is specific to Flutter.
flutter:
  uses-material-design: true